schema: "classroom50/repo-config/v1"
classroom: "agi"
assignment: "todo-app"
owner:
  username: "jo-hyun-sung1469"
  id: 204841569
  accepted_at: "2026-09-08T23:56:14Z"
source:
  owner: "gsm-class"
  owner_id: 318515310
  repo: "todo-app"
  branch: "main"
